### PR TITLE
Torsion wrapper

### PR DESCRIPTION
**Pull request by joshkamm**
@andrewtarzia here is a pull request to continue the stk discussion on extending stk molecules with torsion information in [https://github.com/lukasturcani/stk/discussions/281](https://github.com/lukasturcani/stk/discussions/281)

This is a draft implementation of some basic functionality. There's more that could be done, and more to do cleaning up what I already have, but I've been able to use these classes personally for a couple specific things. I figured it'd be good to get feedback and discuss if / how it would make sense to integrate upstream with stko before I go too much further with it.

A few things that I expect still need some work if it makes sense to integrate into the main stko repo:

*   [ ] Documentation: I have partial documentation but I figured I would ask for some guidelines about how to maintain consistency with the project before finishing it.
*   [ ] Testing: what sort of testing do you have in the rest of the project to be consistent with? Currently I just have some doctests which I see was being considered in stk here: lukasturcani/stk#253
    *   [ ] Look at the tests in the test directory (seem to use pytest)
    *   [ ] Look up pytest
*   [ ] Figuring out how this relates to #57
*   [ ] Probably some code refactoring and restyling for better consistency and integration
    *   [ ] Look at a class module for examples of style choices

### CODE REVIEW

**Comment by andrewtarzia** [comment]
Hey @joshkamm,

Thank you for this! I am liking this functionality. I think a lot of it can be made part of the eventual stko.Molecule and stko.ConstructedMolecule classes, which I am about to get started doing. Plus I need to make the API more consistent throughout stko. I will let you know when the code is ready for this, if that is ok?

As for the testing, you can see examples in the tests directory, although these are also under development at the moment.

In terms of consistency, as I said, stko fits with the same styles as stk, but is slightly inconsistent at the moment. However, a class module file will be a good example of style choices.

Andrew

**Comment by andrewtarzia** [comment]
Hey @joshkamm, 

We are currently working on a more consistent and general way of calculating molecule properties in stko (see #71). I am curious if the following API is ok for you? Here, the last few lines show how you would access all of the Torsion, TorsionInfo and atom_map attributes you have written.

```
import stk
import stko


def main():
    bb1 = stk.BuildingBlock('NCCNCCN', [stk.PrimaryAminoFactory()])
    bb2 = stk.BuildingBlock('O=CCCC=O', [stk.AldehydeFactory()])
    polymer = stk.ConstructedMolecule(
        stk.polymer.Linear(
            building_blocks=(bb1, bb2),
            repeating_unit="AB",
            orientations=[0, 0],
            num_repeating_units=1
        )
    )

    # Run calculations for bb.
    tors_calculator = stko.TorsionCalculator()
    tors_results = tors_calculator.get_results(bb1)
    torsions = tors_results.get_torsions()
    for t in torsions:
        print(t)

    # Run calculations for constructed molecule.
    tors_calculator = stko.ConstructedMoleculeTorsionCalculator()
    tors_results = tors_calculator.get_results(polymer)
    torsions = tors_results.get_torsions()
    for t in torsions:
        print(t)
    torsion_infos = tors_results.get_torsion_infos()
    for t in torsion_infos:
        print(t)
    print(tors_results.get_atom_maps())


if __name__ == "__main__":
    main()

```

**Comment by joshkamm** [comment]
@andrewtarzia to answer your previous question, letting me know when the code is ready sounds good.

Regarding the results API, one nuance I've been having to work with is that rdkit has no knowledge of which building block atoms will be deleted during construction and thus when automatically assigning torsions may arbitrarily choose them when not strictly necessary. Similarly, rdkit's torsions for a constructed molecule may unnecessarily span multiple building blocks. This can substantially reduce the number of torsions that can be associated with individual building blocks. As a workaround I've been manually setting torsions for individual building blocks and wrote `transfer_torsions()` to map these onto a constructed molecule. This workaround could get even messier with ConstructedMoleculeTorsionCalculator, but the workaround doesn't handle torsions that are fundamentally created in construction anyway and there may be a better solution.

Thinking about how to manage torsions created in construction which necessarily span multiple building blocks is something that I've been considering more generally. For my use case, I've been considering implementing functionality that provides an analog of TorsionInfo, but instead of just "get\_building\_block" you would get the smallest aggregate of building blocks that contains the entire torsion.

I guess how to manage this in stko depends on what a typical use case looks like. What would you expect a typical use case for torsions to look like in stko?

**Comment by andrewtarzia** [comment]
If I have understood this correctly, @joshkamm, you are trying to get the torsions in a ConstructedMolecule that are within BuildingBlock and do not included "constructed" bonds? Is that the case? If so, I can think of a way to do that on the whole ConstructedMolecule and then using the ConstructedMolecules `AtomInfo` to discern if a torsion is contained only within a BuildingBlock (i.e. AtomInfo.get_building_block_id() is not None) and then which atoms in the BuildingBlock it is associated with (AtomInfo.get_building_block_atom()).

The benefit of the TorsionCalculator, is that it provides your torsions as defined by the stk molecule, so you can then also filter for Torsions that contain atoms that are `deleters` in the BuildingBlock?

**Comment by joshkamm** [comment]
Not sure if I can explain this clearly, but to give an example of what I'm thinking of imagine taking a butane building block (carbons 1-4 in the sketch below) and a methane building block (call it carbon 5) to construct 2-methylbutane (shown below). If you ask rdkit to compute torsions on this constructed molecule it has symmetrical choices of atom indices to choose for the only torsion: \[1,2,3,4\] OR \[5,2,3,4\]. From rdkit's perspective this choice is arbitrary but it determines whether the torsion atoms all come from the same building block.

**Comment by andrewtarzia** [comment]
I see what you mean. The solution there is, if you know the stk ids (should match the RDKit ids), then you can map that to an AtomInfo, which will tell you the building_block_id, which will be different numbers for the atoms 1 and 5 in your example (or None if they came from a reaction). So you would calculate all torsions, then filter them using these constraints - does that make sense?

**Comment by andrewtarzia** [comment]
Hey @joshkamm  - please look at #77 which introduces what I imagined to be the solution to your problem (look specifically at the example (torsion_example.py).

Would like to discuss this with your further!

**Comment by joshkamm** [comment]
Hey sorry for the delay. I've been thinking about this but was prepping for a talk and hadn't gotten to gather my thoughts into a coherent response. I'll take a deeper look at #77.

**Comment by joshkamm** [comment]
Superseded by #71 , #77 , and #80

**Pull request closed without merging**
